name = "neptune"
license = "MIT"
description = "Neptune is a theme created by Seth Copeland"
tags = ["simple", "clean", "dark", "minimalist", "lightweight"]
features = ["responsive", "darkmode", "portfolio"]
min_version = "1.0"

[author]
    name = "Seth Copeland"
    homepage = "https://seth.nz"
